language: go
go_import_path: github.com/adobe/butler
go:
  - 1.11.x

sudo: false

services:
 - docker

#install:
#  - go get ./...

script:
  - make test

# moved this to the test script in files/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
